# the base image is raspbian stretch lite version
FROM yummygooey/raspbian-buster
LABEL maintainer="asoragna at irobot dot com"

# working directory
ENV HOME /root
WORKDIR $HOME

# minimal ROS2 dependencies
# libc6 is requried because raspbian stretch lite lacks some pthread support
RUN apt-get update && apt-get install -y \
  liblog4cxx-dev \
  libtinyxml2-dev \
  libc6-dev \
  python3-dev

# get ROS2 apt sources
RUN apt-get install -y \
  curl \
  lsb-release
RUN curl -k https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
RUN apt-get update

# eigen --> required for orocos kdl --> required for tf2
# tinyxml --> required for urdf --> required for nav2robot and many other nav packages
RUN apt-get update && apt-get install -y \
  libeigen3-dev \
  libtinyxml-dev

# transform absolute simbolic links into relative ones
RUN apt-get install -y symlinks && symlinks -cr /lib /etc /opt /usr
