# the base image is raspbian stretch lite version
FROM raspbian/stretch
LABEL maintainer="asoragna at irobot dot com"

# working directory
ENV HOME /root
WORKDIR $HOME

# minimal ROS2 dependencies
# libc6 is requried because raspbian stretch lite lacks some pthread support
RUN apt-get update && apt-get install -y \
  libtinyxml2-dev \
  libc6-dev

# get ROS2 apt sources
RUN apt-get install -y \
  curl \
  lsb-release
RUN curl http://repo.ros2.org/repos.key | apt-key add -
RUN sh -c 'echo "deb [arch=amd64,arm64] http://repo.ros2.org/ubuntu/main \
`lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'
RUN apt-get update

# python3.6 support
RUN apt-get install -y \
  python3-dev \
  libffi-dev \
  libssl-dev
RUN wget https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tar.xz
RUN tar xJf Python-3.6.3.tar.xz
WORKDIR Python-3.6.3
RUN apt-get install -y build-essential
RUN apt-get install -y zlib1g-dev
RUN ./configure --prefix=/usr
RUN make
RUN make install

# fix lsb_release to be used with python3.6
RUN ln -s /usr/share/pyshared/lsb_release.py /usr/lib/python3.6/site-packages/lsb_release.py
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3.6 get-pip.py

# TODO: this command fails, so at the moment we are installing it on the host
# numpy --> required for python message_idl_generation
#RUN python3.6 -m pip install numpy

# eigen --> required for orocos kdl --> required for tf2
# tinyxml --> required for urdf --> required for nav2robot and many other nav packages
RUN apt-get update && apt-get install -y \
  libeigen3-dev \
  libtinyxml-dev

# required for nav2_map_server and nav2_util
RUN apt-get install -y \
  libsdl-image1.2 \
  libsdl-image1.2-dev \
  libsdl1.2debian \
  libsdl1.2-dev

# point cloud library needed by costmap 2d
RUN apt-get update && apt-get install -y \
  libopenjp2-7-dev
RUN apt-get update && apt-get install -y \
  libpcl-dev

# required by rcl_logging
RUN apt-get install -y liblog4cxx-dev

# transform absolute simbolic links into relative ones
RUN apt-get install -y symlinks && symlinks -cr /lib /etc /opt /usr
