# Configuration for ActionClient/ActionServer benchmarks

OUTPUT_DIR="actions_single_process"
TOPOLOGIES_DIR="${SCRIPT_DIR}/../../topologies/actions"
TOPOLOGIES=("cli_srv_10b" "cli_srv_100kb" "cli_srv_1mb" "cli_srv_4mb")

# Define RMWs to iterate over
RMW_LIST=("fastrtps" "cyclonedds")

# Define COMMS and env vars for each RMW
COMMS_fastrtps=("ipc_on" "ipc_off")
COMMS_cyclonedds=("ipc_off")
# COMMS_example=()
