# Configuration for Client/Service benchmarks

OUTPUT_DIR="cli-srv_single_process"
TOPOLOGIES=("cli_srv_10b" "cli_srv_100kb" "cli_srv_1mb" "cli_srv_4mb" "10_cli_srv_1mb")
TOPOLOGIES_DIR="${SCRIPT_DIR}/../../topologies/cli-srv"

# Define RMWs to iterate over
RMW_LIST=("fastrtps" "cyclonedds")

# Define COMMS and env vars for each RMW
COMMS_fastrtps=("ipc_on" "ipc_off")
COMMS_cyclonedds=("ipc_off")

# COMMS_example=()
