# Configuration for Pub/Sub benchmarks

OUTPUT_DIR="pub-sub_single_process"
TOPOLOGIES=("pub_sub_10b" "pub_sub_100kb" "pub_sub_1mb" "pub_sub_4mb" "sierra_nevada_fixed_size" "white_mountain_fixed_size")

TOPOLOGIES_DIR="${SCRIPT_DIR}/../../topologies/pub-sub"
PROFILES_DIR="${SCRIPT_DIR}/../../profiles"

# Define RMWs to iterate over
RMW_LIST=("fastrtps" "cyclonedds")

# Define COMMS and env vars for each RMW
COMMS_fastrtps=("ipc_on" "ipc_off" "loaned")
LOANED_ENV_VARS_fastrtps=(
  "export FASTRTPS_DEFAULT_PROFILES_FILE=${PROFILES_DIR}/shared_memory_fastdds_preallocated_w_realloc.xml"
  "export RMW_FASTRTPS_USE_QOS_FROM_XML=1"
)

COMMS_cyclonedds=("ipc_off")
LOANED_ENV_VARS_cyclonedds=(
  "export CYCLONEDDS_URI=${PROFILES_DIR}/shared_memory_cyclonedds.xml"
)

# COMMS_example=()
# LOANED_ENV_VARS_example=()
