struct PerformanceHeader
{
    // builtin_interfaces/Time stamp
    // The seconds component, valid over all int32 values.
    int32 sec;

    // The nanoseconds component, valid in the range [0, 10e9).
    uint32 nanosec;

    uint32 tracking_number;
    float frequency;
    uint32 size;
};