# Configuration for Pub-Sub Multi-Process benchmarks

OUTPUT_DIR="pub-sub_multi_process"
TOPOLOGIES_DIR="${SCRIPT_DIR}/../../topologies/pub-sub"
PROFILES_DIR="${SCRIPT_DIR}/../../profiles"

# Paired topologies
RESULTS=("10b" "100kb" "1mb" "4mb")
TOPOLOGY1=("pub_10b" "pub_100kb" "pub_1mb" "pub_4mb")
TOPOLOGY2=("sub_10b" "sub_100kb" "sub_1mb" "sub_4mb")

# Communication types
RMW_LIST=("fastrtps" "cyclonedds")

# Define COMMS and LOANED_ENV_VARS for each RMW
COMMS_fastrtps=("ipc_off" "loaned")
LOANED_ENV_VARS_fastrtps=(
  "export FASTRTPS_DEFAULT_PROFILES_FILE=${PROFILES_DIR}/shared_memory_fastdds_preallocated_w_realloc.xml"
  "export RMW_FASTRTPS_USE_QOS_FROM_XML=1"
)

COMMS_cyclonedds=("ipc_off")
LOANED_ENV_VARS_cyclonedds=(
  "export CYCLONEDDS_URI=${PROFILES_DIR}/shared_memory_cyclonedds.xml"
)
