# Configuration for ActionClient/ActionServer mix process benchmarks

MEMORY_TOPOLOGIES=(pub_sub_same_topic cli_serv_same_topics default_nodes)

# Communication types
RMW_LIST=("fastrtps" "cyclonedds")
