# Configuration for ActionClient/ActionServer mix process benchmarks

OUTPUT_DIR=memory_results
MEMORY_TEST_BINARIES=(pub_sub_same_topic cli_serv_same_topics)

# TOPOLOGIES_DIR="${SCRIPT_DIR}/../../topologies/actions"
# PROFILES_DIR="${SCRIPT_DIR}/../../profiles"

# Results and topologies
# RESULTS=("10b" "100kb" "1mb" "4mb")
# TOPOLOGY1=("cli_srv_10b" "cli_srv_100kb" "cli_srv_1mb" "cli_srv_4mb")
# TOPOLOGY2=("cli_10b" "cli_100kb" "cli_1mb" "cli_4mb")

# Communication types
# RMW_LIST=("fastrtps" "cyclonedds")

# Define COMMS and LOANED_ENV_VARS for each RMW
# COMMS_fastrtps=("ipc_off")
# COMMS_cyclonedds=("ipc_off")
